In [1]:
from IPython.display import HTML
from IPython.display import display

# Taken from https://stackoverflow.com/questions/31517194/how-to-hide-one-specific-cell-input-or-output-in-ipython-notebook
tag = HTML('''<script>

//https://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/JavaScript%20Notebook%20Extensions.html
$('#run_all_cells, #run_all_cells_above, #run_all_cells_below').click(function() {
    setTimeout(function() {
        // Find running cell and click the first one
        if ($('.running').length > 0) {
            $('.running')[0].click();
        }
    }, 250);
});

code_show=true; 
function code_toggle() {
    if (code_show){
        $('div.cell.code_cell.rendered.selected div.input').hide();
    } else {
        $('div.cell.code_cell.rendered.selected div.input').show();
    }
    code_show = !code_show
} 
$( document ).ready(code_toggle);

</script>
<style>
    @import url('https://fonts.googleapis.com/css?family=Raleway&display=swap');
    
    div.text_cell_render h1 { /* Main titles bigger, centered */
        font-size: 2.2em;
        line-height:1.4em;
        text-align:center;
        color: #00090d;
    }
    div.text_cell_render h2 { /*  Parts names nearer from text */
        font-size: 1.8em;
        color:#f2f2f2;;
        border-radius: 3px;
        background: #2b916a;
        padding: 15px;
        width: 99%;
        height: 2em;
    }
    div.text_cell_render h3 { /*  Parts names nearer from text */
        font-size: 1.5em;
        color:#f2f2f2;
        background: #1eb4a6;
        border-radius: 3px;
        padding: 15px;
        width: 99%;
        height: 2em;
    }
    div.text_cell_render h4 { /*  Parts names nearer from text */
        font-size: 1.2em; 
        font-style: normal;
        color:#f2f2f2;;
        border-radius: 3px;
        background: #008874;
        padding: 5px;
        display: inline-block;
    }
    div.text_cell_render h5 { /*  Parts names nearer from text */
        font-size: 1em;
        font-style: normal;
        color:#f2f2f2;;
        border-radius: 3px;
        background: #0070b8;
        padding: 5px;
        display: inline-block;
    }
    div.text_cell_render h6 { /*  Parts names nearer from text */
        font-size: 1em;
        color: #0082a3;
        font-style: normal;
    }
    
    /* Customize text cells */
    div.text_cell_render { 
        font-family: 'Raleway', sans-serif;
        text-align: justify;
    }    
    
    p,li,span {
        color:#0f0f0f;
        text-align: justify;
    }
       
    .text_cell_render,.rendered_html {
        font-style: normal;
        text-align: justify;
    }
    
    .link_background {
        color: #f2f2f2;
    }

    .box {
      border-radius: 3px;
      border: 2px solid #60b985;
      padding: 20px;
      width: 99%;
      height: 2em;
    }

    .key {
        color: #fdfdfd;
        background-color: #d37a7a;
        padding: 3px;
    }
    .highlight{
        color:#ca5e5e;
        background-color: #fbfacb;
        padding: 3px;
    }
    .mark{
        background-color: #f1d3d3;
        padding: 3px;
    }
    .note{
        background-color: #d9f3d8;
        color: #333333;
        padding: 3px;
    }
    
    .grow{
        font-size: 2em;
        font-weight: bold;
        color: #b31919;
    }
</style>
To show/hide this cell's raw code input, click <a href="javascript:code_toggle()">here</a>.''')
display(tag)

############### Write code below ##################

# The Basics of NumPy Arrays

This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout Data science.

We'll cover a few categories of basic array manipulations here:

- **Attributes of arrays**: Determining the size, shape, memory consumption, and data types of arrays
- **Indexing of arrays**: Getting and setting the value of individual array elements
- **Slicing of arrays**: Getting and setting smaller subarrays within a larger array
- **Reshaping of arrays**: Changing the shape of a given array
- **Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [3]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``, the data type of the array (which we discussed previously.

In [5]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [7]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


<span class='note'>In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.</span>

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[0]

5

In [13]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [15]:
x1[-1]

9

In [16]:
x1[-5]

0

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [17]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [21]:
# Element from 1st Row and 1st Coloumn
x2[0, 0]

3

In [22]:
# Element from 3rd Row and 1st Coloumn
x2[2, 0]

1

In [23]:
# Element from 3rd Row and 3rd Coloumn
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [24]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

<span class='mark'>Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated.</span>

In [25]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
<span class='mark'>If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.</span>
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.